// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"fmt"
	"github.com/bytedance/gopkg/util/logger"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	config2 "github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/google/wire"
	"ppt-agent/biz/ai/llm"
	"ppt-agent/biz/core"
	"ppt-agent/biz/graph/node"
	chat2 "ppt-agent/biz/handler/chat"
	ppt2 "ppt-agent/biz/handler/ppt"
	question2 "ppt-agent/biz/handler/question"
	"ppt-agent/biz/logic/chat"
	"ppt-agent/biz/logic/ppt"
	"ppt-agent/biz/monitor"
	"ppt-agent/biz/router"
	question3 "ppt-agent/biz/service/question"
	session3 "ppt-agent/biz/service/session"
	"ppt-agent/config"
	"strconv"
)

// Injectors from wire.go:

func InitializeApp() (*server.Hertz, error) {
	configConfig := config.InitConfig()
	tokenMonitor := monitor.NewTokenMonitor()
	iPptService := ppt.NewPptService(tokenMonitor)
	pptHandler := ppt2.NewPptHandler(iPptService, tokenMonitor)
	llmWrappers := InitLLMs(configConfig)
	chatModelWrapper := ProvideAgentModel(llmWrappers)
	iSessionService := session3.NewFileSessionService()
	iQuestionService := question3.NewFileQuestionService()
	iChatService := chat.NewChatService(chatModelWrapper, iSessionService)
	chatHandler := chat2.NewChatHandler(iChatService, iSessionService)
	questionHandler := question2.NewQuestionHandler(iQuestionService)
	pptGenerator := core.NewPptGenerator()
	nodeInitializer := InitAllNodes(llmWrappers, pptGenerator)
	hertz := InitServer(configConfig, pptHandler, chatHandler, questionHandler, nodeInitializer)
	return hertz, nil
}

// wire.go:

var configSet = wire.NewSet(config.InitConfig)

var monitorSet = wire.NewSet(monitor.NewTokenMonitor)

var coreSet = wire.NewSet(core.NewPptGenerator)

type LLMWrappers struct {
	TextModel  *llm.ChatModelWrapper  // deepseek-v4-flash — 预检+终检
	AgentModel *llm.ChatModelWrapper  // agnes-2.0-flash — 文案生成+对话
	ImageModel *llm.ImageModelWrapper // agnes-image-2.0-flash — 配图/插画/图表/Logo
}

func InitLLMs(cfg *config.Config) *LLMWrappers {
	return &LLMWrappers{
		TextModel:  llm.NewTextModel(cfg),
		AgentModel: llm.NewAgentModel(cfg),
		ImageModel: llm.NewImageModel(cfg),
	}
}

var llmSet = wire.NewSet(InitLLMs)

// ProvideAgentModel 暴露 AgentModel 给 ChatService
func ProvideAgentModel(wrappers *LLMWrappers) *llm.ChatModelWrapper {
	return wrappers.AgentModel
}

var agentModelSet = wire.NewSet(ProvideAgentModel)

type NodeInitializer struct{}

func InitAllNodes(wrappers *LLMWrappers, pptGen *core.PptGenerator) *NodeInitializer {
	node.InitPptPlanNode(wrappers.AgentModel)
	node.InitPreQualityCheckNode(wrappers.TextModel)
	node.InitPostQualityCheckNode(wrappers.TextModel)
	node.InitImageQualityCheckNode(wrappers.AgentModel)
	node.InitContentImageCollectorNode(wrappers.ImageModel)
	node.InitIllustrationCollectorNode(wrappers.ImageModel)
	node.InitDiagramCollectorNode(wrappers.ImageModel)
	node.InitLogoCollectorNode(wrappers.ImageModel)
	node.InitPptMergeNode(pptGen)
	logger.Info("所有工作流节点已初始化")
	return &NodeInitializer{}
}

var nodeInitSet = wire.NewSet(InitAllNodes)

var serviceSet = wire.NewSet(ppt.NewPptService, chat.NewChatService, session3.NewFileSessionService, question3.NewFileQuestionService)

var handlerSet = wire.NewSet(ppt2.NewPptHandler, chat2.NewChatHandler, question2.NewQuestionHandler)

func CustomRecoveryHandler(ctx context.Context, c *app.RequestContext, err interface{}, stack []byte) {
	logger.Errorf("panic recovered: %v\n%s", err, stack)
	c.JSON(consts.StatusOK, map[string]interface{}{"code": 500, "message": fmt.Sprintf("%v", err)})
	c.Abort()
}

func InitServer(serverConfig *config.Config, pptHandler *ppt2.PptHandler, chatHandler *chat2.ChatHandler, questionHandler *question2.QuestionHandler, _ *NodeInitializer) *server.Hertz {
	serverOpts := []config2.Option{server.WithHostPorts(":" + strconv.Itoa(serverConfig.Server.Port)), server.WithBasePath(serverConfig.Server.ContextPath)}
	h := server.New(serverOpts...)
	h.Use(recovery.Recovery(recovery.WithRecoveryHandler(CustomRecoveryHandler)))
	router.RegisterRoutes(h, pptHandler, chatHandler, questionHandler)
	return h
}
