// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApplyContactReq struct {
	ToId   int64  `json:"toId"`
	Remark string `json:"remark,optional"`
}

type ApplyListResp struct {
	Code    int32     `json:"code,optional"`
	Message string    `json:"message"`
	Data    []ApplyVo `json:"data,optional"`
}

type ApplyVo struct {
	ApplyId  int64  `json:"applyId"`
	FromId   int64  `json:"fromId"`
	Nickname string `json:"nickname,optional"`
	Remark   string `json:"remark,optional"`
	Status   int32  `json:"status"`
}

type CommonResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type ContactInfoReq struct {
	ContactId int64 `json:"contactId"`
}

type ContactListResp struct {
	Code    int32       `json:"code,optional"`
	Message string      `json:"message"`
	Data    []ContactVo `json:"data,optional"`
}

type ContactVo struct {
	ContactId   int64  `json:"contactId"`
	ContactType int32  `json:"contactType"` // 1=好友 2=群聊
	Nickname    string `json:"nickname,optional"`
	Avatar      string `json:"avatar,optional"`
	Status      int32  `json:"status"`
}

type CreateGroupReq struct {
	GroupName string  `json:"groupName"`
	MemberIds []int64 `json:"memberIds,optional"`
}

type CreateSessionReq struct {
	PeerId      int64  `json:"peerId"`
	SessionType int32  `json:"sessionType"` // 1=单聊 2=群聊
	SessionName string `json:"sessionName,optional"`
}

type DeleteSessionReq struct {
	SessionId int64 `json:"sessionId"`
}

type GetGroupMessageReq struct {
	GroupId  int64 `json:"groupId"`
	Page     int64 `json:"page,optional"`
	Size     int64 `json:"size,optional"`
	BeforeId int64 `json:"beforeId,optional"`
}

type GetMessageListReq struct {
	SessionId int64 `json:"sessionId"`
	Page      int64 `json:"page,optional"`
	Size      int64 `json:"size,optional"`
	BeforeId  int64 `json:"beforeId,optional"`
}

type GetUserInfoListReq struct {
	UserIds []int64 `json:"userIds"`
}

type GetUserInfoReq struct {
	UserId int64 `json:"userId,optional"`
}

type GroupIdReq struct {
	GroupId int64 `json:"groupId"`
}

type GroupInfoResp struct {
	Code        int32  `json:"code"`
	Message     string `json:"message"`
	GroupId     int64  `json:"group_id,optional"`
	Name        string `json:"name,optional"`
	Avatar      string `json:"avatar,optional"`
	OwnerId     int64  `json:"owner_id,optional"`
	MemberCount int32  `json:"member_count,optional"`
	AddMode     int32  `json:"add_mode,optional"`
	Status      int32  `json:"status,optional"`
	Notice      string `json:"notice,optional"`
}

type GroupListResp struct {
	Code    int32           `json:"code,optional"`
	Message string          `json:"message"`
	Data    []GroupInfoResp `json:"data,optional"`
}

type GroupMemberListResp struct {
	Code       int32      `json:"code,optional"`
	Message    string     `json:"message"`
	MemberList []MemberVo `json:"memberList,optional"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code     int32  `json:"code"`
	Message  string `json:"message"`
	Token    string `json:"token"`
	UserId   int64  `json:"user_id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type MemberVo struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
	Role     int32  `json:"role"`
	Avatar   string `json:"avatar,optional"`
}

type MessageListResp struct {
	Code    int32       `json:"code,optional"`
	Message string      `json:"message"`
	Data    []MessageVo `json:"data,optional"`
	Total   int64       `json:"total"`
}

type MessageVo struct {
	MsgId      int64  `json:"msgId"`
	SenderId   int64  `json:"senderId"`
	ReceiverId int64  `json:"receiverId"`
	MsgType    int32  `json:"msgType"`
	Content    string `json:"content,optional"`
	FileUrl    string `json:"fileUrl,optional"`
	FileName   string `json:"fileName,optional"`
	FileSize   int64  `json:"fileSize,optional"`
	CreatedAt  int64  `json:"createdAt"`
}

type PassContactApplyReq struct {
	ApplyId int64 `json:"applyId"`
	Status  int32 `json:"status"` // 1=同意 2=拒绝
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
}

type RegisterResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
	UserId  int64  `json:"user_id"`
}

type RemoveMembersReq struct {
	GroupId   int64   `json:"groupId"`
	MemberIds []int64 `json:"memberIds"`
}

type SearchUsersReq struct {
	Keyword string `json:"keyword"`
	Page    int64  `json:"page,optional"`
	Size    int64  `json:"size,optional"`
}

type SearchUsersResp struct {
	Code    int32          `json:"code,optional"`
	Message string         `json:"message"`
	Data    []UserInfoResp `json:"data,optional"`
	Total   int64          `json:"total"`
}

type SessionListResp struct {
	Code    int32       `json:"code,optional"`
	Message string      `json:"message"`
	Data    []SessionVo `json:"data,optional"`
}

type SessionResp struct {
	Code        int32  `json:"code"`
	Message     string `json:"message"`
	SessionId   int64  `json:"sessionId,optional"`
	PeerId      int64  `json:"peerId,optional"`
	SessionType int32  `json:"sessionType,optional"`
	SessionName string `json:"sessionName,optional"`
}

type SessionVo struct {
	SessionId      int64  `json:"sessionId"`
	PeerId         int64  `json:"peerId"`
	SessionType    int32  `json:"sessionType"`
	SessionName    string `json:"sessionName"`
	LastMsgContent string `json:"lastMsgContent,optional"`
	LastMsgTime    int64  `json:"lastMsgTime,optional"`
	UnreadCount    int32  `json:"unreadCount"`
	Avatar         string `json:"avatar,optional"`
}

type SmsCodeReq struct {
	Phone string `json:"phone"`
}

type SmsLoginReq struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type UpdateGroupInfoReq struct {
	GroupId int64  `json:"groupId"`
	Name    string `json:"name,optional"`
	Avatar  string `json:"avatar,optional"`
	Notice  string `json:"notice,optional"`
	AddMode int32  `json:"addMode,optional"`
}

type UpdateUserInfoReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Sex      string `json:"sex,optional"`
	Age      int32  `json:"age,optional"`
	Bio      string `json:"bio,optional"`
}

type UserInfoListResp struct {
	Code    int32          `json:"code,optional"`
	Message string         `json:"message"`
	Data    []UserInfoResp `json:"data,optional"`
}

type UserInfoResp struct {
	Code     int32  `json:"code"`
	Message  string `json:"message"`
	UserId   int64  `json:"user_id,optional"`
	Username string `json:"username,optional"`
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Sex      string `json:"sex,optional"`
	Age      int32  `json:"age,optional"`
	Bio      string `json:"bio,optional"`
	Phone    string `json:"phone,optional"`
	Status   int32  `json:"status,optional"`
	Role     int32  `json:"role,optional"`
}
