// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: voice.proto

package server

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/voice/internal/logic"
	"github.com/your-org/ws-chat-zero/app/voice/internal/svc"
	"github.com/your-org/ws-chat-zero/app/voice/pb/pb"
)

type VoiceServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVoiceServiceServer
}

func NewVoiceServiceServer(svcCtx *svc.ServiceContext) *VoiceServiceServer {
	return &VoiceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *VoiceServiceServer) Recognize(ctx context.Context, in *pb.RecognizeRequest) (*pb.RecognizeResponse, error) {
	l := logic.NewRecognizeLogic(ctx, s.svcCtx)
	return l.Recognize(in)
}
