// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: file.proto

package server

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/file/internal/logic"
	"github.com/your-org/ws-chat-zero/app/file/internal/svc"
	"github.com/your-org/ws-chat-zero/app/file/pb/pb"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServiceServer) UploadFile(ctx context.Context, in *pb.UploadFileRequest) (*pb.UploadFileResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

func (s *FileServiceServer) GetFile(ctx context.Context, in *pb.GetFileRequest) (*pb.GetFileResponse, error) {
	l := logic.NewGetFileLogic(ctx, s.svcCtx)
	return l.GetFile(in)
}

func (s *FileServiceServer) DeleteFile(ctx context.Context, in *pb.DeleteFileRequest) (*pb.CommonResponse, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}
