Name: msg-store
Host: 0.0.0.0
Port: 8084

Log:
  Level: info
  Encoding: plain

Kafka:
  Brokers:
    - kafka:9092
  ChatTopic: chat-messages
  LoginTopic: login
  LogoutTopic: logout
  GroupId: msg-store-group

Mysql:
  DataSource: root:111111@tcp(mysql:3306)/wechat_database?charset=utf8mb4&parseTime=True&loc=Local

ES:
  Addresses:
    - http://elasticsearch:9200
  Index: chat_messages
