// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: friend.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FriendService_GetContactList_FullMethodName     = "/friend.FriendService/GetContactList"
	FriendService_GetContactInfo_FullMethodName     = "/friend.FriendService/GetContactInfo"
	FriendService_ApplyContact_FullMethodName       = "/friend.FriendService/ApplyContact"
	FriendService_PassContactApply_FullMethodName   = "/friend.FriendService/PassContactApply"
	FriendService_DeleteContact_FullMethodName      = "/friend.FriendService/DeleteContact"
	FriendService_BlackContact_FullMethodName       = "/friend.FriendService/BlackContact"
	FriendService_GetApplyList_FullMethodName       = "/friend.FriendService/GetApplyList"
	FriendService_CreateSession_FullMethodName      = "/friend.FriendService/CreateSession"
	FriendService_GetSessionList_FullMethodName     = "/friend.FriendService/GetSessionList"
	FriendService_DeleteSession_FullMethodName      = "/friend.FriendService/DeleteSession"
	FriendService_CreateGroup_FullMethodName        = "/friend.FriendService/CreateGroup"
	FriendService_GetGroupInfo_FullMethodName       = "/friend.FriendService/GetGroupInfo"
	FriendService_GetGroupInfoList_FullMethodName   = "/friend.FriendService/GetGroupInfoList"
	FriendService_UpdateGroupInfo_FullMethodName    = "/friend.FriendService/UpdateGroupInfo"
	FriendService_SetGroupsStatus_FullMethodName    = "/friend.FriendService/SetGroupsStatus"
	FriendService_DeleteGroups_FullMethodName       = "/friend.FriendService/DeleteGroups"
	FriendService_GetGroupMemberList_FullMethodName = "/friend.FriendService/GetGroupMemberList"
	FriendService_DismissGroup_FullMethodName       = "/friend.FriendService/DismissGroup"
	FriendService_LeaveGroup_FullMethodName         = "/friend.FriendService/LeaveGroup"
	FriendService_RemoveGroupMembers_FullMethodName = "/friend.FriendService/RemoveGroupMembers"
)

// FriendServiceClient is the client API for FriendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ── 服务 ──
type FriendServiceClient interface {
	GetContactList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*ContactListResponse, error)
	GetContactInfo(ctx context.Context, in *GetContactInfoRequest, opts ...grpc.CallOption) (*ContactInfoResponse, error)
	ApplyContact(ctx context.Context, in *ApplyContactRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	PassContactApply(ctx context.Context, in *PassContactApplyRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	BlackContact(ctx context.Context, in *BlackContactRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	GetApplyList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*ApplyListResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*SessionListResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error)
	GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error)
	GetGroupInfoList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*GroupListResponse, error)
	UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	SetGroupsStatus(ctx context.Context, in *SetGroupsStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	DeleteGroups(ctx context.Context, in *DeleteGroupsRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	GetGroupMemberList(ctx context.Context, in *GetGroupMemberListRequest, opts ...grpc.CallOption) (*GroupMemberListResponse, error)
	DismissGroup(ctx context.Context, in *DismissGroupRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	RemoveGroupMembers(ctx context.Context, in *RemoveGroupMembersRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type friendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendServiceClient(cc grpc.ClientConnInterface) FriendServiceClient {
	return &friendServiceClient{cc}
}

func (c *friendServiceClient) GetContactList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*ContactListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactListResponse)
	err := c.cc.Invoke(ctx, FriendService_GetContactList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetContactInfo(ctx context.Context, in *GetContactInfoRequest, opts ...grpc.CallOption) (*ContactInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactInfoResponse)
	err := c.cc.Invoke(ctx, FriendService_GetContactInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ApplyContact(ctx context.Context, in *ApplyContactRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_ApplyContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) PassContactApply(ctx context.Context, in *PassContactApplyRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_PassContactApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_DeleteContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) BlackContact(ctx context.Context, in *BlackContactRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_BlackContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetApplyList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*ApplyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyListResponse)
	err := c.cc.Invoke(ctx, FriendService_GetApplyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, FriendService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*SessionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionListResponse)
	err := c.cc.Invoke(ctx, FriendService_GetSessionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInfoResponse)
	err := c.cc.Invoke(ctx, FriendService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInfoResponse)
	err := c.cc.Invoke(ctx, FriendService_GetGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetGroupInfoList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*GroupListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupListResponse)
	err := c.cc.Invoke(ctx, FriendService_GetGroupInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_UpdateGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) SetGroupsStatus(ctx context.Context, in *SetGroupsStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_SetGroupsStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) DeleteGroups(ctx context.Context, in *DeleteGroupsRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_DeleteGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetGroupMemberList(ctx context.Context, in *GetGroupMemberListRequest, opts ...grpc.CallOption) (*GroupMemberListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupMemberListResponse)
	err := c.cc.Invoke(ctx, FriendService_GetGroupMemberList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) DismissGroup(ctx context.Context, in *DismissGroupRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_DismissGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) RemoveGroupMembers(ctx context.Context, in *RemoveGroupMembersRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, FriendService_RemoveGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendServiceServer is the server API for FriendService service.
// All implementations must embed UnimplementedFriendServiceServer
// for forward compatibility.
//
// ── 服务 ──
type FriendServiceServer interface {
	GetContactList(context.Context, *GetContactListRequest) (*ContactListResponse, error)
	GetContactInfo(context.Context, *GetContactInfoRequest) (*ContactInfoResponse, error)
	ApplyContact(context.Context, *ApplyContactRequest) (*CommonResponse, error)
	PassContactApply(context.Context, *PassContactApplyRequest) (*CommonResponse, error)
	DeleteContact(context.Context, *DeleteContactRequest) (*CommonResponse, error)
	BlackContact(context.Context, *BlackContactRequest) (*CommonResponse, error)
	GetApplyList(context.Context, *GetContactListRequest) (*ApplyListResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*SessionResponse, error)
	GetSessionList(context.Context, *GetSessionListRequest) (*SessionListResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*CommonResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*GroupInfoResponse, error)
	GetGroupInfo(context.Context, *GetGroupInfoRequest) (*GroupInfoResponse, error)
	GetGroupInfoList(context.Context, *GetContactListRequest) (*GroupListResponse, error)
	UpdateGroupInfo(context.Context, *UpdateGroupInfoRequest) (*CommonResponse, error)
	SetGroupsStatus(context.Context, *SetGroupsStatusRequest) (*CommonResponse, error)
	DeleteGroups(context.Context, *DeleteGroupsRequest) (*CommonResponse, error)
	GetGroupMemberList(context.Context, *GetGroupMemberListRequest) (*GroupMemberListResponse, error)
	DismissGroup(context.Context, *DismissGroupRequest) (*CommonResponse, error)
	LeaveGroup(context.Context, *LeaveGroupRequest) (*CommonResponse, error)
	RemoveGroupMembers(context.Context, *RemoveGroupMembersRequest) (*CommonResponse, error)
	mustEmbedUnimplementedFriendServiceServer()
}

// UnimplementedFriendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendServiceServer struct{}

func (UnimplementedFriendServiceServer) GetContactList(context.Context, *GetContactListRequest) (*ContactListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContactList not implemented")
}
func (UnimplementedFriendServiceServer) GetContactInfo(context.Context, *GetContactInfoRequest) (*ContactInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContactInfo not implemented")
}
func (UnimplementedFriendServiceServer) ApplyContact(context.Context, *ApplyContactRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyContact not implemented")
}
func (UnimplementedFriendServiceServer) PassContactApply(context.Context, *PassContactApplyRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PassContactApply not implemented")
}
func (UnimplementedFriendServiceServer) DeleteContact(context.Context, *DeleteContactRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteContact not implemented")
}
func (UnimplementedFriendServiceServer) BlackContact(context.Context, *BlackContactRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlackContact not implemented")
}
func (UnimplementedFriendServiceServer) GetApplyList(context.Context, *GetContactListRequest) (*ApplyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplyList not implemented")
}
func (UnimplementedFriendServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedFriendServiceServer) GetSessionList(context.Context, *GetSessionListRequest) (*SessionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionList not implemented")
}
func (UnimplementedFriendServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedFriendServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*GroupInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedFriendServiceServer) GetGroupInfo(context.Context, *GetGroupInfoRequest) (*GroupInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInfo not implemented")
}
func (UnimplementedFriendServiceServer) GetGroupInfoList(context.Context, *GetContactListRequest) (*GroupListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInfoList not implemented")
}
func (UnimplementedFriendServiceServer) UpdateGroupInfo(context.Context, *UpdateGroupInfoRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroupInfo not implemented")
}
func (UnimplementedFriendServiceServer) SetGroupsStatus(context.Context, *SetGroupsStatusRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGroupsStatus not implemented")
}
func (UnimplementedFriendServiceServer) DeleteGroups(context.Context, *DeleteGroupsRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroups not implemented")
}
func (UnimplementedFriendServiceServer) GetGroupMemberList(context.Context, *GetGroupMemberListRequest) (*GroupMemberListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMemberList not implemented")
}
func (UnimplementedFriendServiceServer) DismissGroup(context.Context, *DismissGroupRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DismissGroup not implemented")
}
func (UnimplementedFriendServiceServer) LeaveGroup(context.Context, *LeaveGroupRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedFriendServiceServer) RemoveGroupMembers(context.Context, *RemoveGroupMembersRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGroupMembers not implemented")
}
func (UnimplementedFriendServiceServer) mustEmbedUnimplementedFriendServiceServer() {}
func (UnimplementedFriendServiceServer) testEmbeddedByValue()                       {}

// UnsafeFriendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendServiceServer will
// result in compilation errors.
type UnsafeFriendServiceServer interface {
	mustEmbedUnimplementedFriendServiceServer()
}

func RegisterFriendServiceServer(s grpc.ServiceRegistrar, srv FriendServiceServer) {
	// If the following call panics, it indicates UnimplementedFriendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FriendService_ServiceDesc, srv)
}

func _FriendService_GetContactList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetContactList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetContactList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetContactList(ctx, req.(*GetContactListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetContactInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetContactInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetContactInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetContactInfo(ctx, req.(*GetContactInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ApplyContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ApplyContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ApplyContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ApplyContact(ctx, req.(*ApplyContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_PassContactApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassContactApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).PassContactApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_PassContactApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).PassContactApply(ctx, req.(*PassContactApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_DeleteContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).DeleteContact(ctx, req.(*DeleteContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_BlackContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlackContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).BlackContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_BlackContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).BlackContact(ctx, req.(*BlackContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetApplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetApplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetApplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetApplyList(ctx, req.(*GetContactListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetSessionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetSessionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetSessionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetSessionList(ctx, req.(*GetSessionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetGroupInfo(ctx, req.(*GetGroupInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetGroupInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetGroupInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetGroupInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetGroupInfoList(ctx, req.(*GetContactListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_UpdateGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).UpdateGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_UpdateGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).UpdateGroupInfo(ctx, req.(*UpdateGroupInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_SetGroupsStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupsStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).SetGroupsStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_SetGroupsStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).SetGroupsStatus(ctx, req.(*SetGroupsStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_DeleteGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).DeleteGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_DeleteGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).DeleteGroups(ctx, req.(*DeleteGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetGroupMemberList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMemberListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetGroupMemberList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetGroupMemberList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetGroupMemberList(ctx, req.(*GetGroupMemberListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_DismissGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DismissGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).DismissGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_DismissGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).DismissGroup(ctx, req.(*DismissGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).LeaveGroup(ctx, req.(*LeaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_RemoveGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveGroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).RemoveGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_RemoveGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).RemoveGroupMembers(ctx, req.(*RemoveGroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FriendService_ServiceDesc is the grpc.ServiceDesc for FriendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friend.FriendService",
	HandlerType: (*FriendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContactList",
			Handler:    _FriendService_GetContactList_Handler,
		},
		{
			MethodName: "GetContactInfo",
			Handler:    _FriendService_GetContactInfo_Handler,
		},
		{
			MethodName: "ApplyContact",
			Handler:    _FriendService_ApplyContact_Handler,
		},
		{
			MethodName: "PassContactApply",
			Handler:    _FriendService_PassContactApply_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _FriendService_DeleteContact_Handler,
		},
		{
			MethodName: "BlackContact",
			Handler:    _FriendService_BlackContact_Handler,
		},
		{
			MethodName: "GetApplyList",
			Handler:    _FriendService_GetApplyList_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _FriendService_CreateSession_Handler,
		},
		{
			MethodName: "GetSessionList",
			Handler:    _FriendService_GetSessionList_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _FriendService_DeleteSession_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _FriendService_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroupInfo",
			Handler:    _FriendService_GetGroupInfo_Handler,
		},
		{
			MethodName: "GetGroupInfoList",
			Handler:    _FriendService_GetGroupInfoList_Handler,
		},
		{
			MethodName: "UpdateGroupInfo",
			Handler:    _FriendService_UpdateGroupInfo_Handler,
		},
		{
			MethodName: "SetGroupsStatus",
			Handler:    _FriendService_SetGroupsStatus_Handler,
		},
		{
			MethodName: "DeleteGroups",
			Handler:    _FriendService_DeleteGroups_Handler,
		},
		{
			MethodName: "GetGroupMemberList",
			Handler:    _FriendService_GetGroupMemberList_Handler,
		},
		{
			MethodName: "DismissGroup",
			Handler:    _FriendService_DismissGroup_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _FriendService_LeaveGroup_Handler,
		},
		{
			MethodName: "RemoveGroupMembers",
			Handler:    _FriendService_RemoveGroupMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "friend.proto",
}
