// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: friend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── 实体 ──
type ContactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId     int64                  `protobuf:"varint,3,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	ContactType   int32                  `protobuf:"varint,4,opt,name=contact_type,json=contactType,proto3" json:"contact_type,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{0}
}

func (x *ContactInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactInfo) GetContactId() int64 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

func (x *ContactInfo) GetContactType() int32 {
	if x != nil {
		return x.ContactType
	}
	return 0
}

func (x *ContactInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ContactInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ContactApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId        int64                  `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          int64                  `protobuf:"varint,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ApplyType     int32                  `protobuf:"varint,4,opt,name=apply_type,json=applyType,proto3" json:"apply_type,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApply) Reset() {
	*x = ContactApply{}
	mi := &file_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApply) ProtoMessage() {}

func (x *ContactApply) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApply.ProtoReflect.Descriptor instead.
func (*ContactApply) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{1}
}

func (x *ContactApply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactApply) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *ContactApply) GetToId() int64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *ContactApply) GetApplyType() int32 {
	if x != nil {
		return x.ApplyType
	}
	return 0
}

func (x *ContactApply) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ContactApply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ContactApply) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Session struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PeerId         int64                  `protobuf:"varint,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	SessionType    int32                  `protobuf:"varint,4,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	SessionName    string                 `protobuf:"bytes,5,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	LastMsgId      int64                  `protobuf:"varint,6,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`
	LastMsgContent string                 `protobuf:"bytes,7,opt,name=last_msg_content,json=lastMsgContent,proto3" json:"last_msg_content,omitempty"`
	LastMsgTime    int64                  `protobuf:"varint,8,opt,name=last_msg_time,json=lastMsgTime,proto3" json:"last_msg_time,omitempty"`
	UnreadCount    int32                  `protobuf:"varint,9,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Session) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *Session) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *Session) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *Session) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

func (x *Session) GetLastMsgContent() string {
	if x != nil {
		return x.LastMsgContent
	}
	return ""
}

func (x *Session) GetLastMsgTime() int64 {
	if x != nil {
		return x.LastMsgTime
	}
	return 0
}

func (x *Session) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	OwnerId       int64                  `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	MemberCount   int32                  `protobuf:"varint,5,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	AddMode       int32                  `protobuf:"varint,6,opt,name=add_mode,json=addMode,proto3" json:"add_mode,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Notice        string                 `protobuf:"bytes,8,opt,name=notice,proto3" json:"notice,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{3}
}

func (x *GroupInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupInfo) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GroupInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GroupInfo) GetAddMode() int32 {
	if x != nil {
		return x.AddMode
	}
	return 0
}

func (x *GroupInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupInfo) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *GroupInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{4}
}

func (x *GroupMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMember) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMember) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GroupMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

// ── 请求 ──
type ApplyContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        int64                  `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          int64                  `protobuf:"varint,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyContactRequest) Reset() {
	*x = ApplyContactRequest{}
	mi := &file_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyContactRequest) ProtoMessage() {}

func (x *ApplyContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyContactRequest.ProtoReflect.Descriptor instead.
func (*ApplyContactRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyContactRequest) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *ApplyContactRequest) GetToId() int64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *ApplyContactRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type PassContactApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int64                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassContactApplyRequest) Reset() {
	*x = PassContactApplyRequest{}
	mi := &file_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassContactApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassContactApplyRequest) ProtoMessage() {}

func (x *PassContactApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassContactApplyRequest.ProtoReflect.Descriptor instead.
func (*PassContactApplyRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{6}
}

func (x *PassContactApplyRequest) GetApplyId() int64 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *PassContactApplyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PassContactApplyRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeleteContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId     int64                  `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactRequest) Reset() {
	*x = DeleteContactRequest{}
	mi := &file_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactRequest) ProtoMessage() {}

func (x *DeleteContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactRequest.ProtoReflect.Descriptor instead.
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteContactRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteContactRequest) GetContactId() int64 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

type BlackContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId     int64                  `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlackContactRequest) Reset() {
	*x = BlackContactRequest{}
	mi := &file_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackContactRequest) ProtoMessage() {}

func (x *BlackContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackContactRequest.ProtoReflect.Descriptor instead.
func (*BlackContactRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{8}
}

func (x *BlackContactRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BlackContactRequest) GetContactId() int64 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

type GetContactInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId     int64                  `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactInfoRequest) Reset() {
	*x = GetContactInfoRequest{}
	mi := &file_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactInfoRequest) ProtoMessage() {}

func (x *GetContactInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactInfoRequest.ProtoReflect.Descriptor instead.
func (*GetContactInfoRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{9}
}

func (x *GetContactInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetContactInfoRequest) GetContactId() int64 {
	if x != nil {
		return x.ContactId
	}
	return 0
}

type GetContactListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactListRequest) Reset() {
	*x = GetContactListRequest{}
	mi := &file_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactListRequest) ProtoMessage() {}

func (x *GetContactListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactListRequest.ProtoReflect.Descriptor instead.
func (*GetContactListRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{10}
}

func (x *GetContactListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PeerId        int64                  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	SessionType   int32                  `protobuf:"varint,3,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	SessionName   string                 `protobuf:"bytes,4,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSessionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSessionRequest) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *CreateSessionRequest) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *CreateSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_friend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSessionRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *DeleteSessionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSessionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionType   int32                  `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionListRequest) Reset() {
	*x = GetSessionListRequest{}
	mi := &file_friend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionListRequest) ProtoMessage() {}

func (x *GetSessionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionListRequest.ProtoReflect.Descriptor instead.
func (*GetSessionListRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{13}
}

func (x *GetSessionListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSessionListRequest) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	MemberIds     []int64                `protobuf:"varint,3,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_friend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{14}
}

func (x *CreateGroupRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateGroupRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateGroupRequest) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type DismissGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupRequest) Reset() {
	*x = DismissGroupRequest{}
	mi := &file_friend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupRequest) ProtoMessage() {}

func (x *DismissGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupRequest.ProtoReflect.Descriptor instead.
func (*DismissGroupRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{15}
}

func (x *DismissGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DismissGroupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LeaveGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupRequest) Reset() {
	*x = LeaveGroupRequest{}
	mi := &file_friend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupRequest) ProtoMessage() {}

func (x *LeaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{16}
}

func (x *LeaveGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *LeaveGroupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetGroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoRequest) Reset() {
	*x = GetGroupInfoRequest{}
	mi := &file_friend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoRequest) ProtoMessage() {}

func (x *GetGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{17}
}

func (x *GetGroupInfoRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupMemberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberListRequest) Reset() {
	*x = GetGroupMemberListRequest{}
	mi := &file_friend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberListRequest) ProtoMessage() {}

func (x *GetGroupMemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberListRequest.ProtoReflect.Descriptor instead.
func (*GetGroupMemberListRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{18}
}

func (x *GetGroupMemberListRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type RemoveGroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	MemberIds     []int64                `protobuf:"varint,3,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupMembersRequest) Reset() {
	*x = RemoveGroupMembersRequest{}
	mi := &file_friend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMembersRequest) ProtoMessage() {}

func (x *RemoveGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*RemoveGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveGroupMembersRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RemoveGroupMembersRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *RemoveGroupMembersRequest) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type UpdateGroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Notice        string                 `protobuf:"bytes,4,opt,name=notice,proto3" json:"notice,omitempty"`
	AddMode       int32                  `protobuf:"varint,5,opt,name=add_mode,json=addMode,proto3" json:"add_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupInfoRequest) Reset() {
	*x = UpdateGroupInfoRequest{}
	mi := &file_friend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoRequest) ProtoMessage() {}

func (x *UpdateGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateGroupInfoRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateGroupInfoRequest) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *UpdateGroupInfoRequest) GetAddMode() int32 {
	if x != nil {
		return x.AddMode
	}
	return 0
}

type SetGroupsStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIds      []int64                `protobuf:"varint,1,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupsStatusRequest) Reset() {
	*x = SetGroupsStatusRequest{}
	mi := &file_friend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupsStatusRequest) ProtoMessage() {}

func (x *SetGroupsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupsStatusRequest.ProtoReflect.Descriptor instead.
func (*SetGroupsStatusRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{21}
}

func (x *SetGroupsStatusRequest) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *SetGroupsStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeleteGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIds      []int64                `protobuf:"varint,1,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupsRequest) Reset() {
	*x = DeleteGroupsRequest{}
	mi := &file_friend_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupsRequest) ProtoMessage() {}

func (x *DeleteGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupsRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupsRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteGroupsRequest) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

// ── 响应 ──
type ContactInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ContactInfo           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfoResponse) Reset() {
	*x = ContactInfoResponse{}
	mi := &file_friend_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfoResponse) ProtoMessage() {}

func (x *ContactInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfoResponse.ProtoReflect.Descriptor instead.
func (*ContactInfoResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{23}
}

func (x *ContactInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ContactInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContactInfoResponse) GetData() *ContactInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type ContactListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ContactInfo         `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactListResponse) Reset() {
	*x = ContactListResponse{}
	mi := &file_friend_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListResponse) ProtoMessage() {}

func (x *ContactListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListResponse.ProtoReflect.Descriptor instead.
func (*ContactListResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{24}
}

func (x *ContactListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ContactListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContactListResponse) GetData() []*ContactInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Session               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_friend_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{25}
}

func (x *SessionResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SessionResponse) GetData() *Session {
	if x != nil {
		return x.Data
	}
	return nil
}

type SessionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*Session             `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionListResponse) Reset() {
	*x = SessionListResponse{}
	mi := &file_friend_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionListResponse) ProtoMessage() {}

func (x *SessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionListResponse.ProtoReflect.Descriptor instead.
func (*SessionListResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{26}
}

func (x *SessionListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SessionListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SessionListResponse) GetData() []*Session {
	if x != nil {
		return x.Data
	}
	return nil
}

type GroupInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GroupInfo             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoResponse) Reset() {
	*x = GroupInfoResponse{}
	mi := &file_friend_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoResponse) ProtoMessage() {}

func (x *GroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoResponse.ProtoReflect.Descriptor instead.
func (*GroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{27}
}

func (x *GroupInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GroupInfoResponse) GetData() *GroupInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GroupListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*GroupInfo           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListResponse) Reset() {
	*x = GroupListResponse{}
	mi := &file_friend_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListResponse) ProtoMessage() {}

func (x *GroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListResponse.ProtoReflect.Descriptor instead.
func (*GroupListResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{28}
}

func (x *GroupListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GroupListResponse) GetData() []*GroupInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GroupMemberListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*GroupMember         `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberListResponse) Reset() {
	*x = GroupMemberListResponse{}
	mi := &file_friend_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberListResponse) ProtoMessage() {}

func (x *GroupMemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberListResponse.ProtoReflect.Descriptor instead.
func (*GroupMemberListResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{29}
}

func (x *GroupMemberListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GroupMemberListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GroupMemberListResponse) GetData() []*GroupMember {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApplyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ContactApply        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyListResponse) Reset() {
	*x = ApplyListResponse{}
	mi := &file_friend_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyListResponse) ProtoMessage() {}

func (x *ApplyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyListResponse.ProtoReflect.Descriptor instead.
func (*ApplyListResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{30}
}

func (x *ApplyListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApplyListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApplyListResponse) GetData() []*ContactApply {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_friend_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{31}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_friend_proto protoreflect.FileDescriptor

const file_friend_proto_rawDesc = "" +
	"\n" +
	"\ffriend.proto\x12\x06friend\"\xaf\x01\n" +
	"\vContactInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x03 \x01(\x03R\tcontactId\x12!\n" +
	"\fcontact_type\x18\x04 \x01(\x05R\vcontactType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\xba\x01\n" +
	"\fContactApply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\x03R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\x03R\x04toId\x12\x1d\n" +
	"\n" +
	"apply_type\x18\x04 \x01(\x05R\tapplyType\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xc1\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\x03R\x06peerId\x12!\n" +
	"\fsession_type\x18\x04 \x01(\x05R\vsessionType\x12!\n" +
	"\fsession_name\x18\x05 \x01(\tR\vsessionName\x12\x1e\n" +
	"\vlast_msg_id\x18\x06 \x01(\x03R\tlastMsgId\x12(\n" +
	"\x10last_msg_content\x18\a \x01(\tR\x0elastMsgContent\x12\"\n" +
	"\rlast_msg_time\x18\b \x01(\x03R\vlastMsgTime\x12!\n" +
	"\funread_count\x18\t \x01(\x05R\vunreadCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"\xef\x01\n" +
	"\tGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId\x12!\n" +
	"\fmember_count\x18\x05 \x01(\x05R\vmemberCount\x12\x19\n" +
	"\badd_mode\x18\x06 \x01(\x05R\aaddMode\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x16\n" +
	"\x06notice\x18\b \x01(\tR\x06notice\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"\x9e\x01\n" +
	"\vGroupMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x1b\n" +
	"\tjoined_at\x18\x06 \x01(\x03R\bjoinedAt\"[\n" +
	"\x13ApplyContactRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\x03R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\x03R\x04toId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"e\n" +
	"\x17PassContactApplyRequest\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\x03R\aapplyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"N\n" +
	"\x14DeleteContactRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\x03R\tcontactId\"M\n" +
	"\x13BlackContactRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\x03R\tcontactId\"O\n" +
	"\x15GetContactInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x02 \x01(\x03R\tcontactId\"0\n" +
	"\x15GetContactListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x8e\x01\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x03R\x06peerId\x12!\n" +
	"\fsession_type\x18\x03 \x01(\x05R\vsessionType\x12!\n" +
	"\fsession_name\x18\x04 \x01(\tR\vsessionName\"N\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"S\n" +
	"\x15GetSessionListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fsession_type\x18\x02 \x01(\x05R\vsessionType\"m\n" +
	"\x12CreateGroupRequest\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\x03R\tmemberIds\"I\n" +
	"\x13DismissGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"G\n" +
	"\x11LeaveGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"0\n" +
	"\x13GetGroupInfoRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"6\n" +
	"\x19GetGroupMemberListRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"v\n" +
	"\x19RemoveGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\x03R\tmemberIds\"\x92\x01\n" +
	"\x16UpdateGroupInfoRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06notice\x18\x04 \x01(\tR\x06notice\x12\x19\n" +
	"\badd_mode\x18\x05 \x01(\x05R\aaddMode\"M\n" +
	"\x16SetGroupsStatusRequest\x12\x1b\n" +
	"\tgroup_ids\x18\x01 \x03(\x03R\bgroupIds\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"2\n" +
	"\x13DeleteGroupsRequest\x12\x1b\n" +
	"\tgroup_ids\x18\x01 \x03(\x03R\bgroupIds\"l\n" +
	"\x13ContactInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.friend.ContactInfoR\x04data\"l\n" +
	"\x13ContactListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04data\x18\x03 \x03(\v2\x13.friend.ContactInfoR\x04data\"d\n" +
	"\x0fSessionResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04data\x18\x03 \x01(\v2\x0f.friend.SessionR\x04data\"h\n" +
	"\x13SessionListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04data\x18\x03 \x03(\v2\x0f.friend.SessionR\x04data\"h\n" +
	"\x11GroupInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x04data\x18\x03 \x01(\v2\x11.friend.GroupInfoR\x04data\"h\n" +
	"\x11GroupListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x04data\x18\x03 \x03(\v2\x11.friend.GroupInfoR\x04data\"p\n" +
	"\x17GroupMemberListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04data\x18\x03 \x03(\v2\x13.friend.GroupMemberR\x04data\"k\n" +
	"\x11ApplyListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.friend.ContactApplyR\x04data\">\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd8\v\n" +
	"\rFriendService\x12L\n" +
	"\x0eGetContactList\x12\x1d.friend.GetContactListRequest\x1a\x1b.friend.ContactListResponse\x12L\n" +
	"\x0eGetContactInfo\x12\x1d.friend.GetContactInfoRequest\x1a\x1b.friend.ContactInfoResponse\x12C\n" +
	"\fApplyContact\x12\x1b.friend.ApplyContactRequest\x1a\x16.friend.CommonResponse\x12K\n" +
	"\x10PassContactApply\x12\x1f.friend.PassContactApplyRequest\x1a\x16.friend.CommonResponse\x12E\n" +
	"\rDeleteContact\x12\x1c.friend.DeleteContactRequest\x1a\x16.friend.CommonResponse\x12C\n" +
	"\fBlackContact\x12\x1b.friend.BlackContactRequest\x1a\x16.friend.CommonResponse\x12H\n" +
	"\fGetApplyList\x12\x1d.friend.GetContactListRequest\x1a\x19.friend.ApplyListResponse\x12F\n" +
	"\rCreateSession\x12\x1c.friend.CreateSessionRequest\x1a\x17.friend.SessionResponse\x12L\n" +
	"\x0eGetSessionList\x12\x1d.friend.GetSessionListRequest\x1a\x1b.friend.SessionListResponse\x12E\n" +
	"\rDeleteSession\x12\x1c.friend.DeleteSessionRequest\x1a\x16.friend.CommonResponse\x12D\n" +
	"\vCreateGroup\x12\x1a.friend.CreateGroupRequest\x1a\x19.friend.GroupInfoResponse\x12F\n" +
	"\fGetGroupInfo\x12\x1b.friend.GetGroupInfoRequest\x1a\x19.friend.GroupInfoResponse\x12L\n" +
	"\x10GetGroupInfoList\x12\x1d.friend.GetContactListRequest\x1a\x19.friend.GroupListResponse\x12I\n" +
	"\x0fUpdateGroupInfo\x12\x1e.friend.UpdateGroupInfoRequest\x1a\x16.friend.CommonResponse\x12I\n" +
	"\x0fSetGroupsStatus\x12\x1e.friend.SetGroupsStatusRequest\x1a\x16.friend.CommonResponse\x12C\n" +
	"\fDeleteGroups\x12\x1b.friend.DeleteGroupsRequest\x1a\x16.friend.CommonResponse\x12X\n" +
	"\x12GetGroupMemberList\x12!.friend.GetGroupMemberListRequest\x1a\x1f.friend.GroupMemberListResponse\x12C\n" +
	"\fDismissGroup\x12\x1b.friend.DismissGroupRequest\x1a\x16.friend.CommonResponse\x12?\n" +
	"\n" +
	"LeaveGroup\x12\x19.friend.LeaveGroupRequest\x1a\x16.friend.CommonResponse\x12O\n" +
	"\x12RemoveGroupMembers\x12!.friend.RemoveGroupMembersRequest\x1a\x16.friend.CommonResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_friend_proto_rawDescOnce sync.Once
	file_friend_proto_rawDescData []byte
)

func file_friend_proto_rawDescGZIP() []byte {
	file_friend_proto_rawDescOnce.Do(func() {
		file_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friend_proto_rawDesc), len(file_friend_proto_rawDesc)))
	})
	return file_friend_proto_rawDescData
}

var file_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_friend_proto_goTypes = []any{
	(*ContactInfo)(nil),               // 0: friend.ContactInfo
	(*ContactApply)(nil),              // 1: friend.ContactApply
	(*Session)(nil),                   // 2: friend.Session
	(*GroupInfo)(nil),                 // 3: friend.GroupInfo
	(*GroupMember)(nil),               // 4: friend.GroupMember
	(*ApplyContactRequest)(nil),       // 5: friend.ApplyContactRequest
	(*PassContactApplyRequest)(nil),   // 6: friend.PassContactApplyRequest
	(*DeleteContactRequest)(nil),      // 7: friend.DeleteContactRequest
	(*BlackContactRequest)(nil),       // 8: friend.BlackContactRequest
	(*GetContactInfoRequest)(nil),     // 9: friend.GetContactInfoRequest
	(*GetContactListRequest)(nil),     // 10: friend.GetContactListRequest
	(*CreateSessionRequest)(nil),      // 11: friend.CreateSessionRequest
	(*DeleteSessionRequest)(nil),      // 12: friend.DeleteSessionRequest
	(*GetSessionListRequest)(nil),     // 13: friend.GetSessionListRequest
	(*CreateGroupRequest)(nil),        // 14: friend.CreateGroupRequest
	(*DismissGroupRequest)(nil),       // 15: friend.DismissGroupRequest
	(*LeaveGroupRequest)(nil),         // 16: friend.LeaveGroupRequest
	(*GetGroupInfoRequest)(nil),       // 17: friend.GetGroupInfoRequest
	(*GetGroupMemberListRequest)(nil), // 18: friend.GetGroupMemberListRequest
	(*RemoveGroupMembersRequest)(nil), // 19: friend.RemoveGroupMembersRequest
	(*UpdateGroupInfoRequest)(nil),    // 20: friend.UpdateGroupInfoRequest
	(*SetGroupsStatusRequest)(nil),    // 21: friend.SetGroupsStatusRequest
	(*DeleteGroupsRequest)(nil),       // 22: friend.DeleteGroupsRequest
	(*ContactInfoResponse)(nil),       // 23: friend.ContactInfoResponse
	(*ContactListResponse)(nil),       // 24: friend.ContactListResponse
	(*SessionResponse)(nil),           // 25: friend.SessionResponse
	(*SessionListResponse)(nil),       // 26: friend.SessionListResponse
	(*GroupInfoResponse)(nil),         // 27: friend.GroupInfoResponse
	(*GroupListResponse)(nil),         // 28: friend.GroupListResponse
	(*GroupMemberListResponse)(nil),   // 29: friend.GroupMemberListResponse
	(*ApplyListResponse)(nil),         // 30: friend.ApplyListResponse
	(*CommonResponse)(nil),            // 31: friend.CommonResponse
}
var file_friend_proto_depIdxs = []int32{
	0,  // 0: friend.ContactInfoResponse.data:type_name -> friend.ContactInfo
	0,  // 1: friend.ContactListResponse.data:type_name -> friend.ContactInfo
	2,  // 2: friend.SessionResponse.data:type_name -> friend.Session
	2,  // 3: friend.SessionListResponse.data:type_name -> friend.Session
	3,  // 4: friend.GroupInfoResponse.data:type_name -> friend.GroupInfo
	3,  // 5: friend.GroupListResponse.data:type_name -> friend.GroupInfo
	4,  // 6: friend.GroupMemberListResponse.data:type_name -> friend.GroupMember
	1,  // 7: friend.ApplyListResponse.data:type_name -> friend.ContactApply
	10, // 8: friend.FriendService.GetContactList:input_type -> friend.GetContactListRequest
	9,  // 9: friend.FriendService.GetContactInfo:input_type -> friend.GetContactInfoRequest
	5,  // 10: friend.FriendService.ApplyContact:input_type -> friend.ApplyContactRequest
	6,  // 11: friend.FriendService.PassContactApply:input_type -> friend.PassContactApplyRequest
	7,  // 12: friend.FriendService.DeleteContact:input_type -> friend.DeleteContactRequest
	8,  // 13: friend.FriendService.BlackContact:input_type -> friend.BlackContactRequest
	10, // 14: friend.FriendService.GetApplyList:input_type -> friend.GetContactListRequest
	11, // 15: friend.FriendService.CreateSession:input_type -> friend.CreateSessionRequest
	13, // 16: friend.FriendService.GetSessionList:input_type -> friend.GetSessionListRequest
	12, // 17: friend.FriendService.DeleteSession:input_type -> friend.DeleteSessionRequest
	14, // 18: friend.FriendService.CreateGroup:input_type -> friend.CreateGroupRequest
	17, // 19: friend.FriendService.GetGroupInfo:input_type -> friend.GetGroupInfoRequest
	10, // 20: friend.FriendService.GetGroupInfoList:input_type -> friend.GetContactListRequest
	20, // 21: friend.FriendService.UpdateGroupInfo:input_type -> friend.UpdateGroupInfoRequest
	21, // 22: friend.FriendService.SetGroupsStatus:input_type -> friend.SetGroupsStatusRequest
	22, // 23: friend.FriendService.DeleteGroups:input_type -> friend.DeleteGroupsRequest
	18, // 24: friend.FriendService.GetGroupMemberList:input_type -> friend.GetGroupMemberListRequest
	15, // 25: friend.FriendService.DismissGroup:input_type -> friend.DismissGroupRequest
	16, // 26: friend.FriendService.LeaveGroup:input_type -> friend.LeaveGroupRequest
	19, // 27: friend.FriendService.RemoveGroupMembers:input_type -> friend.RemoveGroupMembersRequest
	24, // 28: friend.FriendService.GetContactList:output_type -> friend.ContactListResponse
	23, // 29: friend.FriendService.GetContactInfo:output_type -> friend.ContactInfoResponse
	31, // 30: friend.FriendService.ApplyContact:output_type -> friend.CommonResponse
	31, // 31: friend.FriendService.PassContactApply:output_type -> friend.CommonResponse
	31, // 32: friend.FriendService.DeleteContact:output_type -> friend.CommonResponse
	31, // 33: friend.FriendService.BlackContact:output_type -> friend.CommonResponse
	30, // 34: friend.FriendService.GetApplyList:output_type -> friend.ApplyListResponse
	25, // 35: friend.FriendService.CreateSession:output_type -> friend.SessionResponse
	26, // 36: friend.FriendService.GetSessionList:output_type -> friend.SessionListResponse
	31, // 37: friend.FriendService.DeleteSession:output_type -> friend.CommonResponse
	27, // 38: friend.FriendService.CreateGroup:output_type -> friend.GroupInfoResponse
	27, // 39: friend.FriendService.GetGroupInfo:output_type -> friend.GroupInfoResponse
	28, // 40: friend.FriendService.GetGroupInfoList:output_type -> friend.GroupListResponse
	31, // 41: friend.FriendService.UpdateGroupInfo:output_type -> friend.CommonResponse
	31, // 42: friend.FriendService.SetGroupsStatus:output_type -> friend.CommonResponse
	31, // 43: friend.FriendService.DeleteGroups:output_type -> friend.CommonResponse
	29, // 44: friend.FriendService.GetGroupMemberList:output_type -> friend.GroupMemberListResponse
	31, // 45: friend.FriendService.DismissGroup:output_type -> friend.CommonResponse
	31, // 46: friend.FriendService.LeaveGroup:output_type -> friend.CommonResponse
	31, // 47: friend.FriendService.RemoveGroupMembers:output_type -> friend.CommonResponse
	28, // [28:48] is the sub-list for method output_type
	8,  // [8:28] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_friend_proto_init() }
func file_friend_proto_init() {
	if File_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friend_proto_rawDesc), len(file_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friend_proto_goTypes,
		DependencyIndexes: file_friend_proto_depIdxs,
		MessageInfos:      file_friend_proto_msgTypes,
	}.Build()
	File_friend_proto = out.File
	file_friend_proto_goTypes = nil
	file_friend_proto_depIdxs = nil
}
