// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package messageservice

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/msg-forward/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetGroupMessageListRequest    = pb.GetGroupMessageListRequest
	GetMessageListRequest         = pb.GetMessageListRequest
	GetRecentMessagesRequest      = pb.GetRecentMessagesRequest
	Message                       = pb.Message
	MessageListResponse           = pb.MessageListResponse
	SearchMessagesRequest         = pb.SearchMessagesRequest
	SendMessageRequest            = pb.SendMessageRequest
	SendMessageResponse           = pb.SendMessageResponse
	DeleteSessionMessagesRequest  = pb.GetRecentMessagesRequest
	DeleteSessionMessagesResponse = pb.SendMessageResponse

	MessageService interface {
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
		GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
		GetGroupMessageList(ctx context.Context, in *GetGroupMessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
		GetRecentMessages(ctx context.Context, in *GetRecentMessagesRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
		SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
		DeleteSessionMessages(ctx context.Context, in *DeleteSessionMessagesRequest, opts ...grpc.CallOption) (*DeleteSessionMessagesResponse, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

func (m *defaultMessageService) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultMessageService) GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessageList(ctx, in, opts...)
}

func (m *defaultMessageService) GetGroupMessageList(ctx context.Context, in *GetGroupMessageListRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetGroupMessageList(ctx, in, opts...)
}

func (m *defaultMessageService) GetRecentMessages(ctx context.Context, in *GetRecentMessagesRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetRecentMessages(ctx, in, opts...)
}

func (m *defaultMessageService) SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SearchMessages(ctx, in, opts...)
}

func (m *defaultMessageService) DeleteSessionMessages(ctx context.Context, in *DeleteSessionMessagesRequest, opts ...grpc.CallOption) (*DeleteSessionMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.DeleteSessionMessages(ctx, in, opts...)
}
