// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package server

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/msg-forward/internal/logic"
	"github.com/your-org/ws-chat-zero/app/msg-forward/internal/svc"
	"github.com/your-org/ws-chat-zero/app/msg-forward/pb/pb"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServiceServer) SendMessage(ctx context.Context, in *pb.SendMessageRequest) (*pb.SendMessageResponse, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *MessageServiceServer) GetMessageList(ctx context.Context, in *pb.GetMessageListRequest) (*pb.MessageListResponse, error) {
	l := logic.NewGetMessageListLogic(ctx, s.svcCtx)
	return l.GetMessageList(in)
}

func (s *MessageServiceServer) GetGroupMessageList(ctx context.Context, in *pb.GetGroupMessageListRequest) (*pb.MessageListResponse, error) {
	l := logic.NewGetGroupMessageListLogic(ctx, s.svcCtx)
	return l.GetGroupMessageList(in)
}

func (s *MessageServiceServer) GetRecentMessages(ctx context.Context, in *pb.GetRecentMessagesRequest) (*pb.MessageListResponse, error) {
	l := logic.NewGetRecentMessagesLogic(ctx, s.svcCtx)
	return l.GetRecentMessages(in)
}

func (s *MessageServiceServer) SearchMessages(ctx context.Context, in *pb.SearchMessagesRequest) (*pb.MessageListResponse, error) {
	l := logic.NewSearchMessagesLogic(ctx, s.svcCtx)
	return l.SearchMessages(in)
}
