// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: voice.proto

package voiceservice

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/voice/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RecognizeRequest  = pb.RecognizeRequest
	RecognizeResponse = pb.RecognizeResponse

	VoiceService interface {
		Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error)
	}

	defaultVoiceService struct {
		cli zrpc.Client
	}
)

func NewVoiceService(cli zrpc.Client) VoiceService {
	return &defaultVoiceService{
		cli: cli,
	}
}

func (m *defaultVoiceService) Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error) {
	client := pb.NewVoiceServiceClient(m.cli.Conn())
	return client.Recognize(ctx, in, opts...)
}
