// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package server

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/friend/internal/logic"
	"github.com/your-org/ws-chat-zero/app/friend/internal/svc"
	"github.com/your-org/ws-chat-zero/app/friend/pb/pb"
)

type FriendServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFriendServiceServer
}

func NewFriendServiceServer(svcCtx *svc.ServiceContext) *FriendServiceServer {
	return &FriendServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendServiceServer) GetContactList(ctx context.Context, in *pb.GetContactListRequest) (*pb.ContactListResponse, error) {
	l := logic.NewGetContactListLogic(ctx, s.svcCtx)
	return l.GetContactList(in)
}

func (s *FriendServiceServer) GetContactInfo(ctx context.Context, in *pb.GetContactInfoRequest) (*pb.ContactInfoResponse, error) {
	l := logic.NewGetContactInfoLogic(ctx, s.svcCtx)
	return l.GetContactInfo(in)
}

func (s *FriendServiceServer) ApplyContact(ctx context.Context, in *pb.ApplyContactRequest) (*pb.CommonResponse, error) {
	l := logic.NewApplyContactLogic(ctx, s.svcCtx)
	return l.ApplyContact(in)
}

func (s *FriendServiceServer) PassContactApply(ctx context.Context, in *pb.PassContactApplyRequest) (*pb.CommonResponse, error) {
	l := logic.NewPassContactApplyLogic(ctx, s.svcCtx)
	return l.PassContactApply(in)
}

func (s *FriendServiceServer) DeleteContact(ctx context.Context, in *pb.DeleteContactRequest) (*pb.CommonResponse, error) {
	l := logic.NewDeleteContactLogic(ctx, s.svcCtx)
	return l.DeleteContact(in)
}

func (s *FriendServiceServer) BlackContact(ctx context.Context, in *pb.BlackContactRequest) (*pb.CommonResponse, error) {
	l := logic.NewBlackContactLogic(ctx, s.svcCtx)
	return l.BlackContact(in)
}

func (s *FriendServiceServer) GetApplyList(ctx context.Context, in *pb.GetContactListRequest) (*pb.ApplyListResponse, error) {
	l := logic.NewGetApplyListLogic(ctx, s.svcCtx)
	return l.GetApplyList(in)
}

func (s *FriendServiceServer) CreateSession(ctx context.Context, in *pb.CreateSessionRequest) (*pb.SessionResponse, error) {
	l := logic.NewCreateSessionLogic(ctx, s.svcCtx)
	return l.CreateSession(in)
}

func (s *FriendServiceServer) GetSessionList(ctx context.Context, in *pb.GetSessionListRequest) (*pb.SessionListResponse, error) {
	l := logic.NewGetSessionListLogic(ctx, s.svcCtx)
	return l.GetSessionList(in)
}

func (s *FriendServiceServer) DeleteSession(ctx context.Context, in *pb.DeleteSessionRequest) (*pb.CommonResponse, error) {
	l := logic.NewDeleteSessionLogic(ctx, s.svcCtx)
	return l.DeleteSession(in)
}

func (s *FriendServiceServer) CreateGroup(ctx context.Context, in *pb.CreateGroupRequest) (*pb.GroupInfoResponse, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *FriendServiceServer) JoinGroup(ctx context.Context, in *pb.DismissGroupRequest) (*pb.CommonResponse, error) {
	l := logic.NewJoinGroupLogic(ctx, s.svcCtx)
	return l.JoinGroup(in)
}

func (s *FriendServiceServer) GetGroupInfo(ctx context.Context, in *pb.GetGroupInfoRequest) (*pb.GroupInfoResponse, error) {
	l := logic.NewGetGroupInfoLogic(ctx, s.svcCtx)
	return l.GetGroupInfo(in)
}

func (s *FriendServiceServer) GetGroupInfoList(ctx context.Context, in *pb.GetContactListRequest) (*pb.GroupListResponse, error) {
	l := logic.NewGetGroupInfoListLogic(ctx, s.svcCtx)
	return l.GetGroupInfoList(in)
}

func (s *FriendServiceServer) UpdateGroupInfo(ctx context.Context, in *pb.UpdateGroupInfoRequest) (*pb.CommonResponse, error) {
	l := logic.NewUpdateGroupInfoLogic(ctx, s.svcCtx)
	return l.UpdateGroupInfo(in)
}

func (s *FriendServiceServer) SetGroupsStatus(ctx context.Context, in *pb.SetGroupsStatusRequest) (*pb.CommonResponse, error) {
	l := logic.NewSetGroupsStatusLogic(ctx, s.svcCtx)
	return l.SetGroupsStatus(in)
}

func (s *FriendServiceServer) DeleteGroups(ctx context.Context, in *pb.DeleteGroupsRequest) (*pb.CommonResponse, error) {
	l := logic.NewDeleteGroupsLogic(ctx, s.svcCtx)
	return l.DeleteGroups(in)
}

func (s *FriendServiceServer) GetGroupMemberList(ctx context.Context, in *pb.GetGroupMemberListRequest) (*pb.GroupMemberListResponse, error) {
	l := logic.NewGetGroupMemberListLogic(ctx, s.svcCtx)
	return l.GetGroupMemberList(in)
}

func (s *FriendServiceServer) DismissGroup(ctx context.Context, in *pb.DismissGroupRequest) (*pb.CommonResponse, error) {
	l := logic.NewDismissGroupLogic(ctx, s.svcCtx)
	return l.DismissGroup(in)
}

func (s *FriendServiceServer) LeaveGroup(ctx context.Context, in *pb.LeaveGroupRequest) (*pb.CommonResponse, error) {
	l := logic.NewLeaveGroupLogic(ctx, s.svcCtx)
	return l.LeaveGroup(in)
}

func (s *FriendServiceServer) RemoveGroupMembers(ctx context.Context, in *pb.RemoveGroupMembersRequest) (*pb.CommonResponse, error) {
	l := logic.NewRemoveGroupMembersLogic(ctx, s.svcCtx)
	return l.RemoveGroupMembers(in)
}
