// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userservice

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/user/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AbleUsersRequest       = pb.AbleUsersRequest
	CommonResponse         = pb.CommonResponse
	DeleteUsersRequest     = pb.DeleteUsersRequest
	DisableUsersRequest    = pb.DisableUsersRequest
	GetUserInfoListRequest = pb.GetUserInfoListRequest
	GetUserInfoRequest     = pb.GetUserInfoRequest
	LoginRequest           = pb.LoginRequest
	LoginResponse          = pb.LoginResponse
	RegisterRequest        = pb.RegisterRequest
	RegisterResponse       = pb.RegisterResponse
	SearchUsersRequest     = pb.SearchUsersRequest
	SearchUsersResponse    = pb.SearchUsersResponse
	SendSmsCodeRequest     = pb.SendSmsCodeRequest
	SetAdminRequest        = pb.SetAdminRequest
	SmsLoginRequest        = pb.SmsLoginRequest
	UpdateUserInfoRequest  = pb.UpdateUserInfoRequest
	UserInfo               = pb.UserInfo
	UserInfoListResponse   = pb.UserInfoListResponse
	UserInfoResponse       = pb.UserInfoResponse
	ValidateTokenRequest   = pb.ValidateTokenRequest
	ValidateTokenResponse  = pb.ValidateTokenResponse
	WsLogoutRequest        = pb.WsLogoutRequest

	UserService interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		SendSmsCode(ctx context.Context, in *SendSmsCodeRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		SmsLogin(ctx context.Context, in *SmsLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		GetUserInfoList(ctx context.Context, in *GetUserInfoListRequest, opts ...grpc.CallOption) (*UserInfoListResponse, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error)
		AbleUsers(ctx context.Context, in *AbleUsersRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		DisableUsers(ctx context.Context, in *DisableUsersRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		DeleteUsers(ctx context.Context, in *DeleteUsersRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		SetAdmin(ctx context.Context, in *SetAdminRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		WsLogout(ctx context.Context, in *WsLogoutRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) SendSmsCode(ctx context.Context, in *SendSmsCodeRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.SendSmsCode(ctx, in, opts...)
}

func (m *defaultUserService) SmsLogin(ctx context.Context, in *SmsLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.SmsLogin(ctx, in, opts...)
}

func (m *defaultUserService) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) GetUserInfoList(ctx context.Context, in *GetUserInfoListRequest, opts ...grpc.CallOption) (*UserInfoListResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfoList(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.SearchUsers(ctx, in, opts...)
}

func (m *defaultUserService) AbleUsers(ctx context.Context, in *AbleUsersRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.AbleUsers(ctx, in, opts...)
}

func (m *defaultUserService) DisableUsers(ctx context.Context, in *DisableUsersRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.DisableUsers(ctx, in, opts...)
}

func (m *defaultUserService) DeleteUsers(ctx context.Context, in *DeleteUsersRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.DeleteUsers(ctx, in, opts...)
}

func (m *defaultUserService) SetAdmin(ctx context.Context, in *SetAdminRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.SetAdmin(ctx, in, opts...)
}

func (m *defaultUserService) WsLogout(ctx context.Context, in *WsLogoutRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.WsLogout(ctx, in, opts...)
}
