// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/user/internal/logic"
	"github.com/your-org/ws-chat-zero/app/user/internal/svc"
	"github.com/your-org/ws-chat-zero/app/user/pb/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) SendSmsCode(ctx context.Context, in *pb.SendSmsCodeRequest) (*pb.CommonResponse, error) {
	l := logic.NewSendSmsCodeLogic(ctx, s.svcCtx)
	return l.SendSmsCode(in)
}

func (s *UserServiceServer) SmsLogin(ctx context.Context, in *pb.SmsLoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewSmsLoginLogic(ctx, s.svcCtx)
	return l.SmsLogin(in)
}

func (s *UserServiceServer) ValidateToken(ctx context.Context, in *pb.ValidateTokenRequest) (*pb.ValidateTokenResponse, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

func (s *UserServiceServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoRequest) (*pb.UserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServiceServer) GetUserInfoList(ctx context.Context, in *pb.GetUserInfoListRequest) (*pb.UserInfoListResponse, error) {
	l := logic.NewGetUserInfoListLogic(ctx, s.svcCtx)
	return l.GetUserInfoList(in)
}

func (s *UserServiceServer) UpdateUserInfo(ctx context.Context, in *pb.UpdateUserInfoRequest) (*pb.CommonResponse, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *UserServiceServer) SearchUsers(ctx context.Context, in *pb.SearchUsersRequest) (*pb.SearchUsersResponse, error) {
	l := logic.NewSearchUsersLogic(ctx, s.svcCtx)
	return l.SearchUsers(in)
}

func (s *UserServiceServer) AbleUsers(ctx context.Context, in *pb.AbleUsersRequest) (*pb.CommonResponse, error) {
	l := logic.NewAbleUsersLogic(ctx, s.svcCtx)
	return l.AbleUsers(in)
}

func (s *UserServiceServer) DisableUsers(ctx context.Context, in *pb.DisableUsersRequest) (*pb.CommonResponse, error) {
	l := logic.NewDisableUsersLogic(ctx, s.svcCtx)
	return l.DisableUsers(in)
}

func (s *UserServiceServer) DeleteUsers(ctx context.Context, in *pb.DeleteUsersRequest) (*pb.CommonResponse, error) {
	l := logic.NewDeleteUsersLogic(ctx, s.svcCtx)
	return l.DeleteUsers(in)
}

func (s *UserServiceServer) SetAdmin(ctx context.Context, in *pb.SetAdminRequest) (*pb.CommonResponse, error) {
	l := logic.NewSetAdminLogic(ctx, s.svcCtx)
	return l.SetAdmin(in)
}

func (s *UserServiceServer) WsLogout(ctx context.Context, in *pb.WsLogoutRequest) (*pb.CommonResponse, error) {
	l := logic.NewWsLogoutLogic(ctx, s.svcCtx)
	return l.WsLogout(in)
}
