// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: file.proto

package fileservice

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/file/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResponse     = pb.CommonResponse
	DeleteFileRequest  = pb.DeleteFileRequest
	GetFileRequest     = pb.GetFileRequest
	GetFileResponse    = pb.GetFileResponse
	UploadFileRequest  = pb.UploadFileRequest
	UploadFileResponse = pb.UploadFileResponse

	FileService interface {
		UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
		GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
		DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	}

	defaultFileService struct {
		cli zrpc.Client
	}
)

func NewFileService(cli zrpc.Client) FileService {
	return &defaultFileService{
		cli: cli,
	}
}

func (m *defaultFileService) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}

func (m *defaultFileService) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.GetFile(ctx, in, opts...)
}

func (m *defaultFileService) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.DeleteFile(ctx, in, opts...)
}
