// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package friendservice

import (
	"context"

	"github.com/your-org/ws-chat-zero/app/friend/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyContactRequest       = pb.ApplyContactRequest
	ApplyListResponse         = pb.ApplyListResponse
	BlackContactRequest       = pb.BlackContactRequest
	CommonResponse            = pb.CommonResponse
	ContactApply              = pb.ContactApply
	ContactInfo               = pb.ContactInfo
	ContactInfoResponse       = pb.ContactInfoResponse
	ContactListResponse       = pb.ContactListResponse
	CreateGroupRequest        = pb.CreateGroupRequest
	CreateSessionRequest      = pb.CreateSessionRequest
	DeleteContactRequest      = pb.DeleteContactRequest
	DeleteGroupsRequest       = pb.DeleteGroupsRequest
	DeleteSessionRequest      = pb.DeleteSessionRequest
	DismissGroupRequest       = pb.DismissGroupRequest
	GetContactInfoRequest     = pb.GetContactInfoRequest
	GetContactListRequest     = pb.GetContactListRequest
	GetGroupInfoRequest       = pb.GetGroupInfoRequest
	GetGroupMemberListRequest = pb.GetGroupMemberListRequest
	GetSessionListRequest     = pb.GetSessionListRequest
	GroupInfo                 = pb.GroupInfo
	GroupInfoResponse         = pb.GroupInfoResponse
	GroupListResponse         = pb.GroupListResponse
	GroupMember               = pb.GroupMember
	GroupMemberListResponse   = pb.GroupMemberListResponse
	LeaveGroupRequest         = pb.LeaveGroupRequest
	PassContactApplyRequest   = pb.PassContactApplyRequest
	RemoveGroupMembersRequest = pb.RemoveGroupMembersRequest
	Session                   = pb.Session
	SessionListResponse       = pb.SessionListResponse
	SessionResponse           = pb.SessionResponse
	SetGroupsStatusRequest    = pb.SetGroupsStatusRequest
	UpdateGroupInfoRequest    = pb.UpdateGroupInfoRequest

	FriendService interface {
		GetContactList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*ContactListResponse, error)
		GetContactInfo(ctx context.Context, in *GetContactInfoRequest, opts ...grpc.CallOption) (*ContactInfoResponse, error)
		ApplyContact(ctx context.Context, in *ApplyContactRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		PassContactApply(ctx context.Context, in *PassContactApplyRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		BlackContact(ctx context.Context, in *BlackContactRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		GetApplyList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*ApplyListResponse, error)
		CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
		GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*SessionListResponse, error)
		DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error)
		GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error)
		GetGroupInfoList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*GroupListResponse, error)
		UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		SetGroupsStatus(ctx context.Context, in *SetGroupsStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		DeleteGroups(ctx context.Context, in *DeleteGroupsRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		GetGroupMemberList(ctx context.Context, in *GetGroupMemberListRequest, opts ...grpc.CallOption) (*GroupMemberListResponse, error)
		DismissGroup(ctx context.Context, in *DismissGroupRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		RemoveGroupMembers(ctx context.Context, in *RemoveGroupMembersRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	}

	defaultFriendService struct {
		cli zrpc.Client
	}
)

func NewFriendService(cli zrpc.Client) FriendService {
	return &defaultFriendService{
		cli: cli,
	}
}

func (m *defaultFriendService) GetContactList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*ContactListResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.GetContactList(ctx, in, opts...)
}

func (m *defaultFriendService) GetContactInfo(ctx context.Context, in *GetContactInfoRequest, opts ...grpc.CallOption) (*ContactInfoResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.GetContactInfo(ctx, in, opts...)
}

func (m *defaultFriendService) ApplyContact(ctx context.Context, in *ApplyContactRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.ApplyContact(ctx, in, opts...)
}

func (m *defaultFriendService) PassContactApply(ctx context.Context, in *PassContactApplyRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.PassContactApply(ctx, in, opts...)
}

func (m *defaultFriendService) DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.DeleteContact(ctx, in, opts...)
}

func (m *defaultFriendService) BlackContact(ctx context.Context, in *BlackContactRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.BlackContact(ctx, in, opts...)
}

func (m *defaultFriendService) GetApplyList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*ApplyListResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.GetApplyList(ctx, in, opts...)
}

func (m *defaultFriendService) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.CreateSession(ctx, in, opts...)
}

func (m *defaultFriendService) GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*SessionListResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.GetSessionList(ctx, in, opts...)
}

func (m *defaultFriendService) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.DeleteSession(ctx, in, opts...)
}

func (m *defaultFriendService) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

func (m *defaultFriendService) GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.GetGroupInfo(ctx, in, opts...)
}

func (m *defaultFriendService) GetGroupInfoList(ctx context.Context, in *GetContactListRequest, opts ...grpc.CallOption) (*GroupListResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.GetGroupInfoList(ctx, in, opts...)
}

func (m *defaultFriendService) UpdateGroupInfo(ctx context.Context, in *UpdateGroupInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.UpdateGroupInfo(ctx, in, opts...)
}

func (m *defaultFriendService) SetGroupsStatus(ctx context.Context, in *SetGroupsStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.SetGroupsStatus(ctx, in, opts...)
}

func (m *defaultFriendService) DeleteGroups(ctx context.Context, in *DeleteGroupsRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.DeleteGroups(ctx, in, opts...)
}

func (m *defaultFriendService) GetGroupMemberList(ctx context.Context, in *GetGroupMemberListRequest, opts ...grpc.CallOption) (*GroupMemberListResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.GetGroupMemberList(ctx, in, opts...)
}

func (m *defaultFriendService) DismissGroup(ctx context.Context, in *DismissGroupRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.DismissGroup(ctx, in, opts...)
}

func (m *defaultFriendService) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.LeaveGroup(ctx, in, opts...)
}

func (m *defaultFriendService) RemoveGroupMembers(ctx context.Context, in *RemoveGroupMembersRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.RemoveGroupMembers(ctx, in, opts...)
}
